-- 코드를 입력하세요


SELECT A.APNT_NO,	PT_NAME, 	P.PT_NO,	D.MCDP_CD,	DR_NAME, 	APNT_YMD
FROM PATIENT P
JOIN APPOINTMENT  A
ON P.PT_NO = A.PT_NO
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE D.MCDP_CD LIKE "CS" -- 흉부외과 
AND A.APNT_YMD LIKE "2022-04-13%" -- 2022년 4월 13일 
AND APNT_CNCL_YN = 'N' -- 취소되지 않음 
ORDER BY A.APNT_YMD ASC -- 진료예약일시를 기준으로 오름차순 정렬